// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoghe4IDWNJav8V9ANJaTWpfP_ChjSLpY',
    appId: '1:816948322608:web:5b31c1f4e4f4e785bb28f5',
    messagingSenderId: '816948322608',
    projectId: 'archify-fb334',
    authDomain: 'archify-fb334.firebaseapp.com',
    storageBucket: 'archify-fb334.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaXR4c6-0ws0okeNiXPI5mzJRudMQ43QQ',
    appId: '1:816948322608:android:1138505a1aab8be0bb28f5',
    messagingSenderId: '816948322608',
    projectId: 'archify-fb334',
    storageBucket: 'archify-fb334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9wKzAJY38-TFzhIRfOzeKrydaxbBQsI',
    appId: '1:816948322608:ios:12fdda7e7f651401bb28f5',
    messagingSenderId: '816948322608',
    projectId: 'archify-fb334',
    storageBucket: 'archify-fb334.appspot.com',
    iosBundleId: 'com.example.archify',
  );
}
